// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/multi_wallet/multi_wallet.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	wallet/multi_wallet/multi_wallet.proto

It has these top-level messages:
	ChainTipReq
	ChainTipResp
	DepositReq
	DepositResp
	WithdrawReq
	WithdrawResp
	GetOmniTransactionReq
	GetOmniTransactionResp
	TransactionCallback
	TransactionOutput
	TransactionInput
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ChainTipReq struct {
	Code       string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	PropertyId string `protobuf:"bytes,2,opt,name=property_id,json=propertyId" json:"property_id,omitempty"`
}

func (m *ChainTipReq) Reset()                    { *m = ChainTipReq{} }
func (m *ChainTipReq) String() string            { return proto1.CompactTextString(m) }
func (*ChainTipReq) ProtoMessage()               {}
func (*ChainTipReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChainTipReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ChainTipReq) GetPropertyId() string {
	if m != nil {
		return m.PropertyId
	}
	return ""
}

type ChainTipResp struct {
	Height uint32 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Hash   string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *ChainTipResp) Reset()                    { *m = ChainTipResp{} }
func (m *ChainTipResp) String() string            { return proto1.CompactTextString(m) }
func (*ChainTipResp) ProtoMessage()               {}
func (*ChainTipResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChainTipResp) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ChainTipResp) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type DepositReq struct {
	Code       string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	PropertyId string `protobuf:"bytes,2,opt,name=property_id,json=propertyId" json:"property_id,omitempty"`
	Purpose    int32  `protobuf:"varint,3,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *DepositReq) Reset()                    { *m = DepositReq{} }
func (m *DepositReq) String() string            { return proto1.CompactTextString(m) }
func (*DepositReq) ProtoMessage()               {}
func (*DepositReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DepositReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DepositReq) GetPropertyId() string {
	if m != nil {
		return m.PropertyId
	}
	return ""
}

func (m *DepositReq) GetPurpose() int32 {
	if m != nil {
		return m.Purpose
	}
	return 0
}

type DepositResp struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *DepositResp) Reset()                    { *m = DepositResp{} }
func (m *DepositResp) String() string            { return proto1.CompactTextString(m) }
func (*DepositResp) ProtoMessage()               {}
func (*DepositResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DepositResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type WithdrawReq struct {
	Code       string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	PropertyId string `protobuf:"bytes,2,opt,name=property_id,json=propertyId" json:"property_id,omitempty"`
	Address    string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Amount     int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	FeeLevel   int32  `protobuf:"varint,5,opt,name=fee_level,json=feeLevel" json:"fee_level,omitempty"`
}

func (m *WithdrawReq) Reset()                    { *m = WithdrawReq{} }
func (m *WithdrawReq) String() string            { return proto1.CompactTextString(m) }
func (*WithdrawReq) ProtoMessage()               {}
func (*WithdrawReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *WithdrawReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *WithdrawReq) GetPropertyId() string {
	if m != nil {
		return m.PropertyId
	}
	return ""
}

func (m *WithdrawReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *WithdrawReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithdrawReq) GetFeeLevel() int32 {
	if m != nil {
		return m.FeeLevel
	}
	return 0
}

type WithdrawResp struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *WithdrawResp) Reset()                    { *m = WithdrawResp{} }
func (m *WithdrawResp) String() string            { return proto1.CompactTextString(m) }
func (*WithdrawResp) ProtoMessage()               {}
func (*WithdrawResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *WithdrawResp) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type GetOmniTransactionReq struct {
	Code string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Txid string `protobuf:"bytes,2,opt,name=txid" json:"txid,omitempty"`
}

func (m *GetOmniTransactionReq) Reset()                    { *m = GetOmniTransactionReq{} }
func (m *GetOmniTransactionReq) String() string            { return proto1.CompactTextString(m) }
func (*GetOmniTransactionReq) ProtoMessage()               {}
func (*GetOmniTransactionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetOmniTransactionReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetOmniTransactionReq) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type GetOmniTransactionResp struct {
	Amount    string `protobuf:"bytes,1,opt,name=amount" json:"amount,omitempty"`
	Fee       string `protobuf:"bytes,2,opt,name=fee" json:"fee,omitempty"`
	Txid      string `protobuf:"bytes,3,opt,name=txid" json:"txid,omitempty"`
	BlockTime int64  `protobuf:"varint,4,opt,name=block_time,json=blockTime" json:"block_time,omitempty"`
}

func (m *GetOmniTransactionResp) Reset()                    { *m = GetOmniTransactionResp{} }
func (m *GetOmniTransactionResp) String() string            { return proto1.CompactTextString(m) }
func (*GetOmniTransactionResp) ProtoMessage()               {}
func (*GetOmniTransactionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetOmniTransactionResp) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetOmniTransactionResp) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *GetOmniTransactionResp) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *GetOmniTransactionResp) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

type TransactionCallback struct {
	Txid      string               `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	Outputs   []*TransactionOutput `protobuf:"bytes,2,rep,name=outputs" json:"outputs,omitempty"`
	Inputs    []*TransactionInput  `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	Height    int32                `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
	Timestamp int64                `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Value     int64                `protobuf:"varint,6,opt,name=value" json:"value,omitempty"`
	WatchOnly bool                 `protobuf:"varint,7,opt,name=watch_only,json=watchOnly" json:"watch_only,omitempty"`
	BlockTime int64                `protobuf:"varint,8,opt,name=block_time,json=blockTime" json:"block_time,omitempty"`
}

func (m *TransactionCallback) Reset()                    { *m = TransactionCallback{} }
func (m *TransactionCallback) String() string            { return proto1.CompactTextString(m) }
func (*TransactionCallback) ProtoMessage()               {}
func (*TransactionCallback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TransactionCallback) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionCallback) GetOutputs() []*TransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *TransactionCallback) GetInputs() []*TransactionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *TransactionCallback) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TransactionCallback) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionCallback) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TransactionCallback) GetWatchOnly() bool {
	if m != nil {
		return m.WatchOnly
	}
	return false
}

func (m *TransactionCallback) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

type TransactionOutput struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Value   int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Index   uint32 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
}

func (m *TransactionOutput) Reset()                    { *m = TransactionOutput{} }
func (m *TransactionOutput) String() string            { return proto1.CompactTextString(m) }
func (*TransactionOutput) ProtoMessage()               {}
func (*TransactionOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TransactionOutput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TransactionOutput) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TransactionOutput) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type TransactionInput struct {
	OutpointHash  []byte `protobuf:"bytes,1,opt,name=outpoint_hash,json=outpointHash,proto3" json:"outpoint_hash,omitempty"`
	OutpointIndex uint32 `protobuf:"varint,2,opt,name=outpoint_index,json=outpointIndex" json:"outpoint_index,omitempty"`
	LinkedAddress string `protobuf:"bytes,3,opt,name=linked_address,json=linkedAddress" json:"linked_address,omitempty"`
	Value         int64  `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *TransactionInput) Reset()                    { *m = TransactionInput{} }
func (m *TransactionInput) String() string            { return proto1.CompactTextString(m) }
func (*TransactionInput) ProtoMessage()               {}
func (*TransactionInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TransactionInput) GetOutpointHash() []byte {
	if m != nil {
		return m.OutpointHash
	}
	return nil
}

func (m *TransactionInput) GetOutpointIndex() uint32 {
	if m != nil {
		return m.OutpointIndex
	}
	return 0
}

func (m *TransactionInput) GetLinkedAddress() string {
	if m != nil {
		return m.LinkedAddress
	}
	return ""
}

func (m *TransactionInput) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto1.RegisterType((*ChainTipReq)(nil), "proto.ChainTipReq")
	proto1.RegisterType((*ChainTipResp)(nil), "proto.ChainTipResp")
	proto1.RegisterType((*DepositReq)(nil), "proto.DepositReq")
	proto1.RegisterType((*DepositResp)(nil), "proto.DepositResp")
	proto1.RegisterType((*WithdrawReq)(nil), "proto.WithdrawReq")
	proto1.RegisterType((*WithdrawResp)(nil), "proto.WithdrawResp")
	proto1.RegisterType((*GetOmniTransactionReq)(nil), "proto.GetOmniTransactionReq")
	proto1.RegisterType((*GetOmniTransactionResp)(nil), "proto.GetOmniTransactionResp")
	proto1.RegisterType((*TransactionCallback)(nil), "proto.TransactionCallback")
	proto1.RegisterType((*TransactionOutput)(nil), "proto.TransactionOutput")
	proto1.RegisterType((*TransactionInput)(nil), "proto.TransactionInput")
}

func init() { proto1.RegisterFile("wallet/multi_wallet/multi_wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xae, 0xed, 0x24, 0x4d, 0x26, 0xc9, 0xab, 0x76, 0xdb, 0xb7, 0x58, 0xa5, 0x15, 0x91, 0x11,
	0x90, 0x53, 0x2b, 0x15, 0xf5, 0xc2, 0x05, 0x41, 0x91, 0xa0, 0x12, 0xa8, 0x92, 0x5b, 0xa9, 0x42,
	0x1c, 0xac, 0x6d, 0x3c, 0xc5, 0xab, 0x3a, 0xf6, 0xe2, 0x5d, 0xf7, 0xe3, 0x37, 0x70, 0xe2, 0x86,
	0xc4, 0x9f, 0x45, 0xbb, 0xde, 0x8d, 0xdd, 0x24, 0xe5, 0x00, 0x27, 0x7b, 0x66, 0x67, 0x9e, 0x79,
	0xe6, 0x13, 0x9e, 0xdf, 0xd0, 0x34, 0x45, 0xb9, 0x3f, 0x2d, 0x53, 0xc9, 0xa2, 0x25, 0xc2, 0x1e,
	0x2f, 0x72, 0x99, 0x93, 0xb6, 0xfe, 0x04, 0x6f, 0xa1, 0x7f, 0x94, 0x50, 0x96, 0x9d, 0x31, 0x1e,
	0xe2, 0x37, 0x42, 0xa0, 0x35, 0xc9, 0x63, 0xf4, 0x9d, 0x91, 0x33, 0xee, 0x85, 0xfa, 0x9f, 0x3c,
	0x81, 0x3e, 0x2f, 0x72, 0x8e, 0x85, 0xbc, 0x8b, 0x58, 0xec, 0xbb, 0xfa, 0x09, 0xac, 0xea, 0x38,
	0x0e, 0x5e, 0xc1, 0xa0, 0xc6, 0x10, 0x9c, 0x6c, 0x41, 0x27, 0x41, 0xf6, 0x35, 0x91, 0x1a, 0x66,
	0x18, 0x1a, 0x49, 0x81, 0x27, 0x54, 0x24, 0x06, 0x41, 0xff, 0x07, 0x5f, 0x00, 0xde, 0x21, 0xcf,
	0x05, 0x93, 0x7f, 0x1b, 0x9e, 0xf8, 0xb0, 0xca, 0xcb, 0x82, 0xe7, 0x02, 0x7d, 0x6f, 0xe4, 0x8c,
	0xdb, 0xa1, 0x15, 0x83, 0x17, 0xd0, 0x9f, 0x81, 0x0b, 0xae, 0x0c, 0x69, 0x1c, 0x17, 0x28, 0x84,
	0x09, 0x60, 0xc5, 0xe0, 0x87, 0x03, 0xfd, 0x73, 0x26, 0x93, 0xb8, 0xa0, 0x37, 0xff, 0xc2, 0xc3,
	0xc2, 0x7b, 0xf7, 0xe0, 0x55, 0x41, 0xe8, 0x34, 0x2f, 0x33, 0xe9, 0xb7, 0x46, 0xce, 0xd8, 0x0b,
	0x8d, 0x44, 0x1e, 0x43, 0xef, 0x12, 0x31, 0x4a, 0xf1, 0x1a, 0x53, 0xbf, 0xad, 0xb9, 0x77, 0x2f,
	0x11, 0x3f, 0x2a, 0x39, 0x08, 0x60, 0x50, 0x53, 0x12, 0x5c, 0x71, 0x92, 0xb7, 0x2c, 0xb6, 0x9c,
	0xd4, 0x7f, 0xf0, 0x1a, 0xfe, 0x7f, 0x8f, 0xf2, 0x64, 0x9a, 0xb1, 0xb3, 0x82, 0x66, 0x82, 0x4e,
	0x24, 0xcb, 0xb3, 0x87, 0x12, 0xb0, 0x00, 0x6e, 0x03, 0xa0, 0x84, 0xad, 0x65, 0x00, 0x55, 0x13,
	0x0d, 0xe7, 0x0a, 0xc3, 0x72, 0x5e, 0x03, 0xef, 0x12, 0xd1, 0x80, 0xa8, 0xdf, 0x19, 0xae, 0x57,
	0xe3, 0x92, 0x5d, 0x80, 0x8b, 0x34, 0x9f, 0x5c, 0x45, 0x92, 0x4d, 0xd1, 0x64, 0xdd, 0xd3, 0x9a,
	0x33, 0x36, 0xc5, 0xe0, 0xa7, 0x0b, 0x1b, 0x8d, 0x80, 0x47, 0x34, 0x4d, 0x2f, 0xe8, 0xe4, 0x6a,
	0x59, 0x8e, 0xe4, 0x00, 0x56, 0xf3, 0x52, 0xf2, 0x52, 0x0a, 0xdf, 0x1d, 0x79, 0xe3, 0xfe, 0x81,
	0x5f, 0x4d, 0xf0, 0x5e, 0x03, 0xe0, 0x44, 0x1b, 0x84, 0xd6, 0x90, 0xec, 0x43, 0x87, 0x65, 0xda,
	0xc5, 0xd3, 0x2e, 0x8f, 0x16, 0x5d, 0x8e, 0xd5, 0x7b, 0x68, 0xcc, 0x1a, 0x23, 0xdb, 0xd2, 0x6d,
	0xb0, 0x23, 0xbb, 0x03, 0x3d, 0x95, 0x81, 0x90, 0x74, 0xca, 0x75, 0x87, 0xbc, 0xb0, 0x56, 0x90,
	0x4d, 0x68, 0x5f, 0xd3, 0xb4, 0x44, 0xbf, 0xa3, 0x5f, 0x2a, 0x41, 0xe5, 0x7e, 0x43, 0xe5, 0x24,
	0x89, 0xf2, 0x2c, 0xbd, 0xf3, 0x57, 0x47, 0xce, 0xb8, 0x1b, 0xf6, 0xb4, 0xe6, 0x24, 0x4b, 0xef,
	0xe6, 0x4a, 0xd3, 0x9d, 0x2f, 0xcd, 0x67, 0x58, 0x5f, 0x48, 0xec, 0xe1, 0xc9, 0xad, 0x29, 0xb8,
	0x4d, 0x0a, 0x9b, 0xd0, 0x66, 0x59, 0x8c, 0xb7, 0xba, 0x27, 0xc3, 0xb0, 0x12, 0x82, 0x5f, 0x0e,
	0xac, 0xcd, 0x57, 0x80, 0x3c, 0x85, 0xa1, 0xaa, 0x5a, 0xce, 0x32, 0x19, 0xe9, 0xed, 0x54, 0x01,
	0x06, 0xe1, 0xc0, 0x2a, 0x3f, 0x50, 0x91, 0x90, 0x67, 0xf0, 0xdf, 0xcc, 0xa8, 0x02, 0x76, 0x35,
	0xf0, 0xcc, 0xf5, 0x58, 0x29, 0x95, 0x59, 0xca, 0xb2, 0x2b, 0x8c, 0xa3, 0xfb, 0x8b, 0x30, 0xac,
	0xb4, 0x6f, 0xe6, 0x39, 0xb7, 0x1a, 0x9c, 0x0f, 0xbe, 0xbb, 0x40, 0x3e, 0xa9, 0x3b, 0x75, 0xae,
	0xcf, 0xd4, 0x29, 0x16, 0xd7, 0x6c, 0x82, 0xe4, 0x10, 0xba, 0xf6, 0xb8, 0x10, 0x62, 0xda, 0xd8,
	0xb8, 0x58, 0xdb, 0x1b, 0x0b, 0x3a, 0xc1, 0x83, 0x15, 0x35, 0x35, 0x66, 0xf5, 0xc9, 0xba, 0xb1,
	0xa8, 0xef, 0xcc, 0x36, 0x99, 0x57, 0x69, 0x9f, 0x43, 0xe8, 0xda, 0x8d, 0x9b, 0x85, 0x6a, 0x5c,
	0x85, 0x59, 0xa8, 0xe6, 0x5a, 0x06, 0x2b, 0xe4, 0x14, 0xc8, 0xe2, 0x0e, 0x91, 0x1d, 0x63, 0xbc,
	0x74, 0x3f, 0xb7, 0x77, 0xff, 0xf0, 0xaa, 0x40, 0x2f, 0x3a, 0xfa, 0xfd, 0xe5, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x00, 0xe7, 0xef, 0xcf, 0x05, 0x00, 0x00,
}
