// This code was autogenerated from backend/user/user.proto, do not edit.
package proto

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	nats "github.com/nats-io/go-nats"
	"github.com/nats-rpc/nrpc"
)

// UserServiceServer is the interface that providers of the service
// UserService should implement.
type UserServiceServer interface {
	GetUser(ctx context.Context, req GetUserReq) (resp UserInfo, err error)
	GetUserByInternalAddress(ctx context.Context, req GetUserByInternalAddressReq) (resp UserInfo, err error)
	IsExist(ctx context.Context, req IsExistReq) (resp IsExistResp, err error)
}

// UserServiceHandler provides a NATS subscription handler that can serve a
// subscription using a given UserServiceServer implementation.
type UserServiceHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  UserServiceServer
}

func NewUserServiceHandler(ctx context.Context, nc nrpc.NatsConn, s UserServiceServer) *UserServiceHandler {
	return &UserServiceHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,
	}
}

func NewUserServiceConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s UserServiceServer) *UserServiceHandler {
	return &UserServiceHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

func (h *UserServiceHandler) Subject() string {
	return "proto.UserService.>"
}

func (h *UserServiceHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"proto", 0, "UserService", 0, msg.Subject)
	if err != nil {
		log.Printf("UserServiceHanlder: UserService subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "GetUser":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("GetUserHanlder: GetUser subject parsing failed: %v", err)
			break
		}
		var req GetUserReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("GetUserHandler: GetUser request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.GetUser(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "GetUserByInternalAddress":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("GetUserByInternalAddressHanlder: GetUserByInternalAddress subject parsing failed: %v", err)
			break
		}
		var req GetUserByInternalAddressReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("GetUserByInternalAddressHandler: GetUserByInternalAddress request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.GetUserByInternalAddress(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "IsExist":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("IsExistHanlder: IsExist subject parsing failed: %v", err)
			break
		}
		var req IsExistReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("IsExistHandler: IsExist request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.IsExist(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	default:
		log.Printf("UserServiceHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("UserServiceHandler: UserService handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type UserServiceClient struct {
	nc      nrpc.NatsConn
	PkgSubject string
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewUserServiceClient(nc nrpc.NatsConn) *UserServiceClient {
	return &UserServiceClient{
		nc:      nc,
		PkgSubject: "proto",
		Subject: "UserService",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *UserServiceClient) GetUser(req GetUserReq) (resp UserInfo, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "GetUser"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *UserServiceClient) GetUserByInternalAddress(req GetUserByInternalAddressReq) (resp UserInfo, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "GetUserByInternalAddress"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *UserServiceClient) IsExist(req IsExistReq) (resp IsExistResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "IsExist"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	pkgSubject string
	UserService *UserServiceClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
		pkgSubject: "proto",
	}
	c.UserService = NewUserServiceClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.UserService != nil {
		c.UserService.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.UserService != nil {
		c.UserService.Timeout = t
	}
}