// This code was autogenerated from exchange_rate/exchange_rate.proto, do not edit.
package proto

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	nats "github.com/nats-io/go-nats"
	"github.com/nats-rpc/nrpc"
)

// ExchangeRateServiceServer is the interface that providers of the service
// ExchangeRateService should implement.
type ExchangeRateServiceServer interface {
	GetAllRates(ctx context.Context, req GetAllRatesReq) (resp GetAllRatesResp, err error)
	GetExchangeRate(ctx context.Context, req GetExchangeRateReq) (resp GetExchangeRateResp, err error)
	GetLatestRate(ctx context.Context, req GetExchangeRateReq) (resp GetExchangeRateResp, err error)
}

// ExchangeRateServiceHandler provides a NATS subscription handler that can serve a
// subscription using a given ExchangeRateServiceServer implementation.
type ExchangeRateServiceHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  ExchangeRateServiceServer
}

func NewExchangeRateServiceHandler(ctx context.Context, nc nrpc.NatsConn, s ExchangeRateServiceServer) *ExchangeRateServiceHandler {
	return &ExchangeRateServiceHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,
	}
}

func NewExchangeRateServiceConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s ExchangeRateServiceServer) *ExchangeRateServiceHandler {
	return &ExchangeRateServiceHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

func (h *ExchangeRateServiceHandler) Subject() string {
	return "proto.ExchangeRateService.>"
}

func (h *ExchangeRateServiceHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"proto", 0, "ExchangeRateService", 0, msg.Subject)
	if err != nil {
		log.Printf("ExchangeRateServiceHanlder: ExchangeRateService subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "GetAllRates":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("GetAllRatesHanlder: GetAllRates subject parsing failed: %v", err)
			break
		}
		var req GetAllRatesReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("GetAllRatesHandler: GetAllRates request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.GetAllRates(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "GetExchangeRate":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("GetExchangeRateHanlder: GetExchangeRate subject parsing failed: %v", err)
			break
		}
		var req GetExchangeRateReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("GetExchangeRateHandler: GetExchangeRate request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.GetExchangeRate(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "GetLatestRate":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("GetLatestRateHanlder: GetLatestRate subject parsing failed: %v", err)
			break
		}
		var req GetExchangeRateReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("GetLatestRateHandler: GetLatestRate request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.GetLatestRate(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	default:
		log.Printf("ExchangeRateServiceHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("ExchangeRateServiceHandler: ExchangeRateService handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type ExchangeRateServiceClient struct {
	nc      nrpc.NatsConn
	PkgSubject string
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewExchangeRateServiceClient(nc nrpc.NatsConn) *ExchangeRateServiceClient {
	return &ExchangeRateServiceClient{
		nc:      nc,
		PkgSubject: "proto",
		Subject: "ExchangeRateService",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *ExchangeRateServiceClient) GetAllRates(req GetAllRatesReq) (resp GetAllRatesResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "GetAllRates"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *ExchangeRateServiceClient) GetExchangeRate(req GetExchangeRateReq) (resp GetExchangeRateResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "GetExchangeRate"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *ExchangeRateServiceClient) GetLatestRate(req GetExchangeRateReq) (resp GetExchangeRateResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "GetLatestRate"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	pkgSubject string
	ExchangeRateService *ExchangeRateServiceClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
		pkgSubject: "proto",
	}
	c.ExchangeRateService = NewExchangeRateServiceClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.ExchangeRateService != nil {
		c.ExchangeRateService.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.ExchangeRateService != nil {
		c.ExchangeRateService.Timeout = t
	}
}