[eos_wallet_service]
name = "eos_wallet_service"
url = "wss://ws.eospark.com/v1/ws?apikey=48f594e19edb52c71e6e7011ec90c9e4"
platform_account = "mnmdgod55aaa"
port = 9012

[nats]
url = "nats://192.168.0.231:4222"
