// Code generated by protoc-gen-go. DO NOT EDIT.
// source: front/front.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	front/front.proto

It has these top-level messages:
	RecvPushReq
	RecvPushResp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RecvPushReq struct {
	Uid    uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	MsgId  int64  `protobuf:"varint,2,opt,name=msgId" json:"msgId,omitempty"`
	Title  string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Text   string `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	Custom []byte `protobuf:"bytes,5,opt,name=custom,proto3" json:"custom,omitempty"`
}

func (m *RecvPushReq) Reset()                    { *m = RecvPushReq{} }
func (m *RecvPushReq) String() string            { return proto1.CompactTextString(m) }
func (*RecvPushReq) ProtoMessage()               {}
func (*RecvPushReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RecvPushReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RecvPushReq) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *RecvPushReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RecvPushReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *RecvPushReq) GetCustom() []byte {
	if m != nil {
		return m.Custom
	}
	return nil
}

type RecvPushResp struct {
	ErrNo int32  `protobuf:"varint,1,opt,name=errNo" json:"errNo,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *RecvPushResp) Reset()                    { *m = RecvPushResp{} }
func (m *RecvPushResp) String() string            { return proto1.CompactTextString(m) }
func (*RecvPushResp) ProtoMessage()               {}
func (*RecvPushResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RecvPushResp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *RecvPushResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*RecvPushReq)(nil), "proto.RecvPushReq")
	proto1.RegisterType((*RecvPushResp)(nil), "proto.RecvPushResp")
}

func init() { proto1.RegisterFile("front/front.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x85, 0x8d, 0x6d, 0x4a, 0x7b, 0xed, 0xa0, 0x57, 0x91, 0xe0, 0x14, 0x3a, 0x65, 0xaa, 0x50,
	0xd1, 0xdd, 0x45, 0x70, 0x50, 0xca, 0xfd, 0x09, 0xb6, 0xb1, 0x16, 0xac, 0xa9, 0x49, 0xaa, 0xfe,
	0x7c, 0x49, 0xa2, 0xbc, 0x07, 0x6f, 0x49, 0xce, 0xf9, 0x86, 0x73, 0xee, 0x81, 0xb3, 0x57, 0x6b,
	0x3e, 0xfc, 0x75, 0x7c, 0xdb, 0xd5, 0x1a, 0x6f, 0x90, 0xc7, 0xaf, 0xf9, 0x86, 0x13, 0xd2, 0xc3,
	0x57, 0xbf, 0xb9, 0x37, 0xd2, 0x9f, 0x78, 0x0a, 0xd9, 0x36, 0x8f, 0x82, 0x49, 0xa6, 0x72, 0x0a,
	0x12, 0x2f, 0x80, 0x2f, 0x6e, 0x7a, 0x1c, 0xc5, 0xb1, 0x64, 0x2a, 0xa3, 0x64, 0x02, 0xf5, 0xb3,
	0x7f, 0xd7, 0x22, 0x93, 0x4c, 0x55, 0x94, 0x0c, 0x22, 0xe4, 0x5e, 0xff, 0x78, 0x91, 0x47, 0x18,
	0x35, 0x5e, 0x42, 0x31, 0x6c, 0xce, 0x9b, 0x45, 0x70, 0xc9, 0x54, 0x4d, 0x7f, 0xae, 0xb9, 0x83,
	0x7a, 0x57, 0xec, 0xd6, 0x90, 0xa8, 0xad, 0x7d, 0x36, 0xb1, 0x9b, 0x53, 0x32, 0xe1, 0x9e, 0xc5,
	0x4d, 0xb1, 0xbb, 0xa2, 0x20, 0xbb, 0x7b, 0x28, 0x1f, 0xc2, 0x8c, 0xbe, 0x7b, 0xc2, 0x5b, 0x28,
	0xff, 0x33, 0x10, 0xd3, 0xae, 0x76, 0x6f, 0xcd, 0xd5, 0xf9, 0x01, 0x73, 0x6b, 0x73, 0xf4, 0x52,
	0x44, 0x7a, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x73, 0xdf, 0xd6, 0x65, 0x16, 0x01, 0x00, 0x00,
}
