// This code was autogenerated from front/front.proto, do not edit.
package proto

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	nats "github.com/nats-io/go-nats"
	"github.com/nats-rpc/nrpc"
)

// FrontP2MServer is the interface that providers of the service
// FrontP2M should implement.
type FrontP2MServer interface {
	RecvPush(ctx context.Context, req RecvPushReq) (resp RecvPushResp, err error)
}

// FrontP2MHandler provides a NATS subscription handler that can serve a
// subscription using a given FrontP2MServer implementation.
type FrontP2MHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  FrontP2MServer
}

func NewFrontP2MHandler(ctx context.Context, nc nrpc.NatsConn, s FrontP2MServer) *FrontP2MHandler {
	return &FrontP2MHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,
	}
}

func NewFrontP2MConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s FrontP2MServer) *FrontP2MHandler {
	return &FrontP2MHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

func (h *FrontP2MHandler) Subject() string {
	return "proto.FrontP2M.>"
}

func (h *FrontP2MHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"proto", 0, "FrontP2M", 0, msg.Subject)
	if err != nil {
		log.Printf("FrontP2MHanlder: FrontP2M subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "RecvPush":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RecvPushHanlder: RecvPush subject parsing failed: %v", err)
			break
		}
		var req RecvPushReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RecvPushHandler: RecvPush request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RecvPush(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	default:
		log.Printf("FrontP2MHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("FrontP2MHandler: FrontP2M handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type FrontP2MClient struct {
	nc      nrpc.NatsConn
	PkgSubject string
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewFrontP2MClient(nc nrpc.NatsConn) *FrontP2MClient {
	return &FrontP2MClient{
		nc:      nc,
		PkgSubject: "proto",
		Subject: "FrontP2M",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *FrontP2MClient) RecvPush(req RecvPushReq) (resp RecvPushResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "RecvPush"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	pkgSubject string
	FrontP2M *FrontP2MClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
		pkgSubject: "proto",
	}
	c.FrontP2M = NewFrontP2MClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.FrontP2M != nil {
		c.FrontP2M.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.FrontP2M != nil {
		c.FrontP2M.Timeout = t
	}
}