// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/eos_wallet/eos_wallet.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	wallet/eos_wallet/eos_wallet.proto

It has these top-level messages:
	DepositReq
	DepositResp
	EosWithdrawReq
	EosWithdrawResp
	TransactionCallback
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DepositReq struct {
	Purpose int32 `protobuf:"varint,1,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *DepositReq) Reset()                    { *m = DepositReq{} }
func (m *DepositReq) String() string            { return proto1.CompactTextString(m) }
func (*DepositReq) ProtoMessage()               {}
func (*DepositReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DepositReq) GetPurpose() int32 {
	if m != nil {
		return m.Purpose
	}
	return 0
}

type DepositResp struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *DepositResp) Reset()                    { *m = DepositResp{} }
func (m *DepositResp) String() string            { return proto1.CompactTextString(m) }
func (*DepositResp) ProtoMessage()               {}
func (*DepositResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DepositResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type EosWithdrawReq struct {
	To    string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *EosWithdrawReq) Reset()                    { *m = EosWithdrawReq{} }
func (m *EosWithdrawReq) String() string            { return proto1.CompactTextString(m) }
func (*EosWithdrawReq) ProtoMessage()               {}
func (*EosWithdrawReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EosWithdrawReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EosWithdrawReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EosWithdrawResp struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *EosWithdrawResp) Reset()                    { *m = EosWithdrawResp{} }
func (m *EosWithdrawResp) String() string            { return proto1.CompactTextString(m) }
func (*EosWithdrawResp) ProtoMessage()               {}
func (*EosWithdrawResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EosWithdrawResp) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type TransactionCallback struct {
	IsDeposit bool   `protobuf:"varint,1,opt,name=is_deposit,json=isDeposit" json:"is_deposit,omitempty"`
	Txid      string `protobuf:"bytes,2,opt,name=txid" json:"txid,omitempty"`
	From      string `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	To        string `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Contract  string `protobuf:"bytes,5,opt,name=contract" json:"contract,omitempty"`
	Status    uint64 `protobuf:"varint,6,opt,name=status" json:"status,omitempty"`
	Quantity  string `protobuf:"bytes,7,opt,name=quantity" json:"quantity,omitempty"`
	Memo      string `protobuf:"bytes,8,opt,name=memo" json:"memo,omitempty"`
	BlockTime int64  `protobuf:"varint,9,opt,name=block_time,json=blockTime" json:"block_time,omitempty"`
}

func (m *TransactionCallback) Reset()                    { *m = TransactionCallback{} }
func (m *TransactionCallback) String() string            { return proto1.CompactTextString(m) }
func (*TransactionCallback) ProtoMessage()               {}
func (*TransactionCallback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TransactionCallback) GetIsDeposit() bool {
	if m != nil {
		return m.IsDeposit
	}
	return false
}

func (m *TransactionCallback) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionCallback) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionCallback) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionCallback) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *TransactionCallback) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TransactionCallback) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *TransactionCallback) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *TransactionCallback) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func init() {
	proto1.RegisterType((*DepositReq)(nil), "proto.DepositReq")
	proto1.RegisterType((*DepositResp)(nil), "proto.DepositResp")
	proto1.RegisterType((*EosWithdrawReq)(nil), "proto.EosWithdrawReq")
	proto1.RegisterType((*EosWithdrawResp)(nil), "proto.EosWithdrawResp")
	proto1.RegisterType((*TransactionCallback)(nil), "proto.TransactionCallback")
}

func init() { proto1.RegisterFile("wallet/eos_wallet/eos_wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4e, 0xe3, 0x30,
	0x18, 0xdc, 0xa4, 0x4d, 0xdb, 0x7c, 0x95, 0xba, 0xbb, 0xde, 0xa5, 0xb2, 0x2a, 0x21, 0x55, 0x91,
	0x80, 0x9e, 0x8a, 0x54, 0x24, 0x8e, 0x5c, 0x80, 0x17, 0x08, 0x95, 0x38, 0x56, 0x6e, 0x62, 0x84,
	0xd5, 0x24, 0x76, 0xed, 0x2f, 0x2d, 0xbc, 0x00, 0xaf, 0xcb, 0x2b, 0x20, 0x3b, 0x3f, 0xa5, 0xc0,
	0x29, 0xdf, 0x4c, 0x66, 0x3e, 0x8f, 0x3d, 0x10, 0xed, 0x59, 0x96, 0x71, 0xbc, 0xe4, 0xd2, 0xac,
	0xbe, 0x8d, 0x73, 0xa5, 0x25, 0x4a, 0x12, 0xb8, 0x4f, 0x74, 0x0e, 0x70, 0xc7, 0x95, 0x34, 0x02,
	0x63, 0xbe, 0x25, 0x14, 0xfa, 0xaa, 0xd4, 0x4a, 0x1a, 0x4e, 0xbd, 0xa9, 0x37, 0x0b, 0xe2, 0x06,
	0x46, 0x17, 0x30, 0x6c, 0x75, 0x46, 0x59, 0x21, 0x4b, 0x53, 0xcd, 0x8d, 0x71, 0xc2, 0x30, 0x6e,
	0x60, 0x74, 0x0d, 0xa3, 0x7b, 0x69, 0x1e, 0x05, 0x3e, 0xa7, 0x9a, 0xed, 0xed, 0xd2, 0x11, 0xf8,
	0x28, 0x6b, 0x99, 0x8f, 0x92, 0xfc, 0x87, 0x60, 0xc7, 0xb2, 0x92, 0x53, 0xdf, 0x51, 0x15, 0x88,
	0xce, 0xe0, 0xf7, 0x91, 0xcf, 0x28, 0x42, 0xa0, 0x8b, 0x2f, 0x22, 0xad, 0xad, 0x6e, 0x8e, 0xde,
	0x3d, 0xf8, 0xb7, 0xd4, 0xac, 0x30, 0x2c, 0x41, 0x21, 0x8b, 0x5b, 0x96, 0x65, 0x6b, 0x96, 0x6c,
	0xc8, 0x29, 0x80, 0x30, 0xab, 0xb4, 0x8a, 0xe8, 0x1c, 0x83, 0x38, 0x14, 0xa6, 0xce, 0xdc, 0xae,
	0xf2, 0x0f, 0xab, 0x2c, 0xf7, 0xa4, 0x65, 0x4e, 0x3b, 0x15, 0x67, 0xe7, 0x3a, 0x6b, 0xb7, 0xcd,
	0x3a, 0x81, 0x41, 0x22, 0x0b, 0xd4, 0x2c, 0x41, 0x1a, 0x38, 0xb6, 0xc5, 0x64, 0x0c, 0x3d, 0x83,
	0x0c, 0x4b, 0x43, 0x7b, 0x53, 0x6f, 0xd6, 0x8d, 0x6b, 0x64, 0x3d, 0xdb, 0x92, 0x15, 0x28, 0xf0,
	0x95, 0xf6, 0x2b, 0x4f, 0x83, 0xed, 0x99, 0x39, 0xcf, 0x25, 0x1d, 0x54, 0x67, 0xda, 0xd9, 0x46,
	0x5f, 0x67, 0x32, 0xd9, 0xac, 0x50, 0xe4, 0x9c, 0x86, 0x53, 0x6f, 0xd6, 0x89, 0x43, 0xc7, 0x2c,
	0x45, 0xce, 0x17, 0x6f, 0x1e, 0xfc, 0xb1, 0x2f, 0xe3, 0xca, 0x7b, 0xe0, 0x7a, 0x27, 0x12, 0x4e,
	0x16, 0xd0, 0x6f, 0xae, 0xf6, 0xb7, 0x2a, 0x74, 0x7e, 0xa8, 0x71, 0x42, 0xbe, 0x52, 0x46, 0x45,
	0xbf, 0xc8, 0x0d, 0x0c, 0x3f, 0xbd, 0x30, 0x39, 0xa9, 0x45, 0xc7, 0x6d, 0x4d, 0xc6, 0x3f, 0xd1,
	0xd6, 0xbf, 0xee, 0xb9, 0x1f, 0x57, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x95, 0x4c, 0x6c,
	0x5e, 0x02, 0x00, 0x00,
}
