// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push/push.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	push/push.proto

It has these top-level messages:
	LogoutReq
	LogoutResp
	SendMsgReq
	SendMsgResp
	DeviceInfoReq
	DeviceInfoResp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type LogoutReq struct {
	UserId uint64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	AppId  int32  `protobuf:"varint,2,opt,name=appId" json:"appId,omitempty"`
}

func (m *LogoutReq) Reset()                    { *m = LogoutReq{} }
func (m *LogoutReq) String() string            { return proto1.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()               {}
func (*LogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogoutReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LogoutReq) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

type LogoutResp struct {
	ErrNo int32  `protobuf:"varint,1,opt,name=errNo" json:"errNo,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *LogoutResp) Reset()                    { *m = LogoutResp{} }
func (m *LogoutResp) String() string            { return proto1.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()               {}
func (*LogoutResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogoutResp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *LogoutResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SendMsgReq struct {
	DisplayType string `protobuf:"bytes,1,opt,name=displayType" json:"displayType,omitempty"`
	Receivers   string `protobuf:"bytes,2,opt,name=receivers" json:"receivers,omitempty"`
	AppId       int32  `protobuf:"varint,3,opt,name=appId" json:"appId,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Text        string `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	Custom      []byte `protobuf:"bytes,6,opt,name=custom,proto3" json:"custom,omitempty"`
	ExpireTime  int32  `protobuf:"varint,7,opt,name=expireTime" json:"expireTime,omitempty"`
	LoginStatus int32  `protobuf:"varint,8,opt,name=loginStatus" json:"loginStatus,omitempty"`
}

func (m *SendMsgReq) Reset()                    { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string            { return proto1.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()               {}
func (*SendMsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SendMsgReq) GetDisplayType() string {
	if m != nil {
		return m.DisplayType
	}
	return ""
}

func (m *SendMsgReq) GetReceivers() string {
	if m != nil {
		return m.Receivers
	}
	return ""
}

func (m *SendMsgReq) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *SendMsgReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SendMsgReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SendMsgReq) GetCustom() []byte {
	if m != nil {
		return m.Custom
	}
	return nil
}

func (m *SendMsgReq) GetExpireTime() int32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *SendMsgReq) GetLoginStatus() int32 {
	if m != nil {
		return m.LoginStatus
	}
	return 0
}

type SendMsgResp struct {
	ErrNo int32  `protobuf:"varint,1,opt,name=errNo" json:"errNo,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *SendMsgResp) Reset()                    { *m = SendMsgResp{} }
func (m *SendMsgResp) String() string            { return proto1.CompactTextString(m) }
func (*SendMsgResp) ProtoMessage()               {}
func (*SendMsgResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendMsgResp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *SendMsgResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeviceInfoReq struct {
	AppId       int32  `protobuf:"varint,1,opt,name=appId" json:"appId,omitempty"`
	DeviceToken string `protobuf:"bytes,2,opt,name=deviceToken" json:"deviceToken,omitempty"`
	PushType    int32  `protobuf:"varint,3,opt,name=pushType" json:"pushType,omitempty"`
	Uid         uint64 `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	Platform    int32  `protobuf:"varint,5,opt,name=platform" json:"platform,omitempty"`
}

func (m *DeviceInfoReq) Reset()                    { *m = DeviceInfoReq{} }
func (m *DeviceInfoReq) String() string            { return proto1.CompactTextString(m) }
func (*DeviceInfoReq) ProtoMessage()               {}
func (*DeviceInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeviceInfoReq) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *DeviceInfoReq) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *DeviceInfoReq) GetPushType() int32 {
	if m != nil {
		return m.PushType
	}
	return 0
}

func (m *DeviceInfoReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DeviceInfoReq) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

type DeviceInfoResp struct {
	ErrNo int32  `protobuf:"varint,1,opt,name=errNo" json:"errNo,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *DeviceInfoResp) Reset()                    { *m = DeviceInfoResp{} }
func (m *DeviceInfoResp) String() string            { return proto1.CompactTextString(m) }
func (*DeviceInfoResp) ProtoMessage()               {}
func (*DeviceInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeviceInfoResp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *DeviceInfoResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*LogoutReq)(nil), "proto.LogoutReq")
	proto1.RegisterType((*LogoutResp)(nil), "proto.LogoutResp")
	proto1.RegisterType((*SendMsgReq)(nil), "proto.SendMsgReq")
	proto1.RegisterType((*SendMsgResp)(nil), "proto.SendMsgResp")
	proto1.RegisterType((*DeviceInfoReq)(nil), "proto.DeviceInfoReq")
	proto1.RegisterType((*DeviceInfoResp)(nil), "proto.DeviceInfoResp")
}

func init() { proto1.RegisterFile("push/push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x8e, 0x94, 0x40,
	0x10, 0x15, 0x77, 0x60, 0x96, 0x5a, 0x5d, 0xd7, 0xca, 0x6a, 0x08, 0x31, 0x86, 0x70, 0x9a, 0xd3,
	0x6e, 0x82, 0x9a, 0xe8, 0xc9, 0x8b, 0x97, 0x31, 0xae, 0x99, 0xf4, 0xcc, 0x0f, 0x20, 0xd4, 0xb2,
	0x1d, 0x81, 0x6e, 0xbb, 0x9b, 0xcd, 0xce, 0x67, 0xf8, 0x93, 0x7e, 0x87, 0xe9, 0x86, 0x01, 0x9c,
	0x78, 0xd0, 0x0b, 0xf4, 0x7b, 0xbc, 0x57, 0x5d, 0xf5, 0x28, 0x78, 0x26, 0x3b, 0x7d, 0x77, 0x6d,
	0x1f, 0x57, 0x52, 0x09, 0x23, 0xd0, 0x77, 0xaf, 0xf4, 0x03, 0x84, 0x5f, 0x44, 0x25, 0x3a, 0xc3,
	0xe8, 0x07, 0xbe, 0x84, 0xa0, 0xd3, 0xa4, 0xd6, 0x65, 0xe4, 0x25, 0xde, 0x6a, 0xc1, 0x06, 0x84,
	0x97, 0xe0, 0xe7, 0x52, 0xae, 0xcb, 0xe8, 0x71, 0xe2, 0xad, 0x7c, 0xd6, 0x83, 0xf4, 0x2d, 0xc0,
	0xc1, 0xaa, 0xa5, 0xd5, 0x90, 0x52, 0x5f, 0x85, 0xb3, 0xfa, 0xac, 0x07, 0x78, 0x01, 0x27, 0x8d,
	0xae, 0x9c, 0x2f, 0x64, 0xf6, 0x98, 0xfe, 0xf2, 0x00, 0xb6, 0xd4, 0x96, 0x37, 0xba, 0xb2, 0x57,
	0x26, 0x70, 0x56, 0x72, 0x2d, 0xeb, 0x7c, 0xbf, 0xdb, 0x4b, 0x72, 0xe6, 0x90, 0xcd, 0x29, 0x7c,
	0x05, 0xa1, 0xa2, 0x82, 0xf8, 0x3d, 0x29, 0x3d, 0x14, 0x9a, 0x88, 0xa9, 0xb5, 0x93, 0x59, 0x6b,
	0x96, 0x35, 0xdc, 0xd4, 0x14, 0x2d, 0x9c, 0xbe, 0x07, 0x88, 0xb0, 0x30, 0xf4, 0x60, 0x22, 0xdf,
	0x91, 0xee, 0x6c, 0x47, 0x2e, 0x3a, 0x6d, 0x44, 0x13, 0x05, 0x89, 0xb7, 0x7a, 0xc2, 0x06, 0x84,
	0xaf, 0x01, 0xe8, 0x41, 0x72, 0x45, 0x3b, 0xde, 0x50, 0xb4, 0x74, 0xc5, 0x67, 0x8c, 0xed, 0xbb,
	0x16, 0x15, 0x6f, 0xb7, 0x26, 0x37, 0x9d, 0x8e, 0x4e, 0x9d, 0x60, 0x4e, 0xa5, 0xef, 0xe0, 0x6c,
	0x9c, 0xf3, 0x3f, 0xf2, 0xf9, 0xe9, 0xc1, 0xd3, 0x4f, 0x74, 0xcf, 0x0b, 0x5a, 0xb7, 0xb7, 0xc2,
	0x46, 0x34, 0x8e, 0xe8, 0xcd, 0x47, 0xb4, 0xc1, 0x39, 0xd9, 0x4e, 0x7c, 0xa7, 0x76, 0xa8, 0x30,
	0xa7, 0x30, 0x86, 0x53, 0xfb, 0xbf, 0x5d, 0xae, 0x7d, 0x3a, 0x23, 0xb6, 0xf7, 0x76, 0xbc, 0x74,
	0xf1, 0x2c, 0x98, 0x3d, 0x3a, 0x75, 0x9d, 0x9b, 0x5b, 0xa1, 0x1a, 0x17, 0x90, 0x55, 0x0f, 0x38,
	0x7d, 0x0f, 0xe7, 0xf3, 0x96, 0xfe, 0x7d, 0x9a, 0xac, 0x85, 0xe5, 0xa6, 0xd3, 0x77, 0x9b, 0x6c,
	0x83, 0xd7, 0x10, 0xf4, 0xeb, 0x82, 0x17, 0xfd, 0x0a, 0x5e, 0x8d, 0x8b, 0x17, 0x3f, 0x3f, 0x62,
	0xb4, 0x4c, 0x1f, 0x61, 0x06, 0xcb, 0x21, 0x40, 0x3c, 0x7c, 0x9f, 0x16, 0x27, 0xc6, 0x63, 0xca,
	0x7a, 0xb2, 0xcf, 0x87, 0xfb, 0x6e, 0xf0, 0x23, 0x9c, 0x6f, 0xf7, 0x6d, 0x31, 0x35, 0x8e, 0x97,
	0x83, 0xe5, 0x8f, 0x78, 0xe3, 0x17, 0x7f, 0x61, 0x6d, 0xad, 0x6f, 0x81, 0xe3, 0xdf, 0xfc, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0xd4, 0xfc, 0xa5, 0x3b, 0x03, 0x00, 0x00,
}
