dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
install:
  - npm install -g truffle
  - npm install
before_script:
  - truffle version
script:
  - npm run lint:sol
  - npm run coverage