// This code was autogenerated from im/im.proto, do not edit.
package proto

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	nats "github.com/nats-io/go-nats"
	"github.com/nats-rpc/nrpc"
)

// IMServiceServer is the interface that providers of the service
// IMService should implement.
type IMServiceServer interface {
	UserRegister(ctx context.Context, req UserRegisterReq) (resp UserRegisterResp, err error)
	UserUpdate(ctx context.Context, req UserUpdateReq) (resp UserUpdateResp, err error)
	SendSysMsg(ctx context.Context, req SendSysMsgReq) (resp SendSysMsgResp, err error)
}

// IMServiceHandler provides a NATS subscription handler that can serve a
// subscription using a given IMServiceServer implementation.
type IMServiceHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  IMServiceServer
}

func NewIMServiceHandler(ctx context.Context, nc nrpc.NatsConn, s IMServiceServer) *IMServiceHandler {
	return &IMServiceHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,
	}
}

func NewIMServiceConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s IMServiceServer) *IMServiceHandler {
	return &IMServiceHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

func (h *IMServiceHandler) Subject() string {
	return "proto.IMService.>"
}

func (h *IMServiceHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"proto", 0, "IMService", 0, msg.Subject)
	if err != nil {
		log.Printf("IMServiceHanlder: IMService subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "UserRegister":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("UserRegisterHanlder: UserRegister subject parsing failed: %v", err)
			break
		}
		var req UserRegisterReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("UserRegisterHandler: UserRegister request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.UserRegister(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "UserUpdate":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("UserUpdateHanlder: UserUpdate subject parsing failed: %v", err)
			break
		}
		var req UserUpdateReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("UserUpdateHandler: UserUpdate request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.UserUpdate(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "SendSysMsg":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("SendSysMsgHanlder: SendSysMsg subject parsing failed: %v", err)
			break
		}
		var req SendSysMsgReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("SendSysMsgHandler: SendSysMsg request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.SendSysMsg(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	default:
		log.Printf("IMServiceHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("IMServiceHandler: IMService handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type IMServiceClient struct {
	nc      nrpc.NatsConn
	PkgSubject string
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewIMServiceClient(nc nrpc.NatsConn) *IMServiceClient {
	return &IMServiceClient{
		nc:      nc,
		PkgSubject: "proto",
		Subject: "IMService",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *IMServiceClient) UserRegister(req UserRegisterReq) (resp UserRegisterResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "UserRegister"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *IMServiceClient) UserUpdate(req UserUpdateReq) (resp UserUpdateResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "UserUpdate"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *IMServiceClient) SendSysMsg(req SendSysMsgReq) (resp SendSysMsgResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "SendSysMsg"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	pkgSubject string
	IMService *IMServiceClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
		pkgSubject: "proto",
	}
	c.IMService = NewIMServiceClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.IMService != nil {
		c.IMService.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.IMService != nil {
		c.IMService.Timeout = t
	}
}