// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/private_wallet/private_wallet.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	wallet/private_wallet/private_wallet.proto

It has these top-level messages:
	ChainTipReq
	ChainTipResp
	AddressResp
	TransferReq
	TransferResp
	NewAddressReq
	TransactionReq
	TransactionResp
	DeployTokenReq
	GetTokenBalanceReq
	GetTokenBalanceResp
	TokenReq
	TokenResp
	TransactionErrorCallback
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ChainTipReq struct {
}

func (m *ChainTipReq) Reset()                    { *m = ChainTipReq{} }
func (m *ChainTipReq) String() string            { return proto1.CompactTextString(m) }
func (*ChainTipReq) ProtoMessage()               {}
func (*ChainTipReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChainTipResp struct {
	Height uint32 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Hash   string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *ChainTipResp) Reset()                    { *m = ChainTipResp{} }
func (m *ChainTipResp) String() string            { return proto1.CompactTextString(m) }
func (*ChainTipResp) ProtoMessage()               {}
func (*ChainTipResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChainTipResp) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ChainTipResp) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type AddressResp struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *AddressResp) Reset()                    { *m = AddressResp{} }
func (m *AddressResp) String() string            { return proto1.CompactTextString(m) }
func (*AddressResp) ProtoMessage()               {}
func (*AddressResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type TransferReq struct {
	To    string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *TransferReq) Reset()                    { *m = TransferReq{} }
func (m *TransferReq) String() string            { return proto1.CompactTextString(m) }
func (*TransferReq) ProtoMessage()               {}
func (*TransferReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransferReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransferReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TransferResp struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *TransferResp) Reset()                    { *m = TransferResp{} }
func (m *TransferResp) String() string            { return proto1.CompactTextString(m) }
func (*TransferResp) ProtoMessage()               {}
func (*TransferResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TransferResp) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type NewAddressReq struct {
	Purpose int32 `protobuf:"varint,1,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *NewAddressReq) Reset()                    { *m = NewAddressReq{} }
func (m *NewAddressReq) String() string            { return proto1.CompactTextString(m) }
func (*NewAddressReq) ProtoMessage()               {}
func (*NewAddressReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NewAddressReq) GetPurpose() int32 {
	if m != nil {
		return m.Purpose
	}
	return 0
}

type TransactionReq struct {
	Amount        string `protobuf:"bytes,1,opt,name=amount" json:"amount,omitempty"`
	Sn            string `protobuf:"bytes,2,opt,name=sn" json:"sn,omitempty"`
	Threshold     int32  `protobuf:"varint,3,opt,name=threshold" json:"threshold,omitempty"`
	Timeout       int64  `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	BuyerAddress  string `protobuf:"bytes,5,opt,name=buyer_address,json=buyerAddress" json:"buyer_address,omitempty"`
	SellerAddress string `protobuf:"bytes,6,opt,name=seller_address,json=sellerAddress" json:"seller_address,omitempty"`
	TokenAddress  string `protobuf:"bytes,7,opt,name=token_address,json=tokenAddress" json:"token_address,omitempty"`
	To            int32  `protobuf:"varint,8,opt,name=to" json:"to,omitempty"`
}

func (m *TransactionReq) Reset()                    { *m = TransactionReq{} }
func (m *TransactionReq) String() string            { return proto1.CompactTextString(m) }
func (*TransactionReq) ProtoMessage()               {}
func (*TransactionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TransactionReq) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TransactionReq) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *TransactionReq) GetThreshold() int32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *TransactionReq) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *TransactionReq) GetBuyerAddress() string {
	if m != nil {
		return m.BuyerAddress
	}
	return ""
}

func (m *TransactionReq) GetSellerAddress() string {
	if m != nil {
		return m.SellerAddress
	}
	return ""
}

func (m *TransactionReq) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *TransactionReq) GetTo() int32 {
	if m != nil {
		return m.To
	}
	return 0
}

type TransactionResp struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *TransactionResp) Reset()                    { *m = TransactionResp{} }
func (m *TransactionResp) String() string            { return proto1.CompactTextString(m) }
func (*TransactionResp) ProtoMessage()               {}
func (*TransactionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TransactionResp) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type DeployTokenReq struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Symbol   string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Decimals uint32 `protobuf:"varint,3,opt,name=decimals" json:"decimals,omitempty"`
}

func (m *DeployTokenReq) Reset()                    { *m = DeployTokenReq{} }
func (m *DeployTokenReq) String() string            { return proto1.CompactTextString(m) }
func (*DeployTokenReq) ProtoMessage()               {}
func (*DeployTokenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeployTokenReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployTokenReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *DeployTokenReq) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

type GetTokenBalanceReq struct {
	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress" json:"token_address,omitempty"`
	WhoAddress   string `protobuf:"bytes,2,opt,name=who_address,json=whoAddress" json:"who_address,omitempty"`
}

func (m *GetTokenBalanceReq) Reset()                    { *m = GetTokenBalanceReq{} }
func (m *GetTokenBalanceReq) String() string            { return proto1.CompactTextString(m) }
func (*GetTokenBalanceReq) ProtoMessage()               {}
func (*GetTokenBalanceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetTokenBalanceReq) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *GetTokenBalanceReq) GetWhoAddress() string {
	if m != nil {
		return m.WhoAddress
	}
	return ""
}

type GetTokenBalanceResp struct {
	Balance string `protobuf:"bytes,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *GetTokenBalanceResp) Reset()                    { *m = GetTokenBalanceResp{} }
func (m *GetTokenBalanceResp) String() string            { return proto1.CompactTextString(m) }
func (*GetTokenBalanceResp) ProtoMessage()               {}
func (*GetTokenBalanceResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetTokenBalanceResp) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type TokenReq struct {
	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress" json:"token_address,omitempty"`
	WhoAddress   string `protobuf:"bytes,2,opt,name=who_address,json=whoAddress" json:"who_address,omitempty"`
	Amount       string `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
}

func (m *TokenReq) Reset()                    { *m = TokenReq{} }
func (m *TokenReq) String() string            { return proto1.CompactTextString(m) }
func (*TokenReq) ProtoMessage()               {}
func (*TokenReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *TokenReq) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *TokenReq) GetWhoAddress() string {
	if m != nil {
		return m.WhoAddress
	}
	return ""
}

func (m *TokenReq) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type TokenResp struct {
}

func (m *TokenResp) Reset()                    { *m = TokenResp{} }
func (m *TokenResp) String() string            { return proto1.CompactTextString(m) }
func (*TokenResp) ProtoMessage()               {}
func (*TokenResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type TransactionErrorCallback struct {
	IsDeposit    bool   `protobuf:"varint,1,opt,name=is_deposit,json=isDeposit" json:"is_deposit,omitempty"`
	TokenAddress string `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress" json:"token_address,omitempty"`
	WhoAddress   string `protobuf:"bytes,3,opt,name=who_address,json=whoAddress" json:"who_address,omitempty"`
}

func (m *TransactionErrorCallback) Reset()                    { *m = TransactionErrorCallback{} }
func (m *TransactionErrorCallback) String() string            { return proto1.CompactTextString(m) }
func (*TransactionErrorCallback) ProtoMessage()               {}
func (*TransactionErrorCallback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *TransactionErrorCallback) GetIsDeposit() bool {
	if m != nil {
		return m.IsDeposit
	}
	return false
}

func (m *TransactionErrorCallback) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *TransactionErrorCallback) GetWhoAddress() string {
	if m != nil {
		return m.WhoAddress
	}
	return ""
}

func init() {
	proto1.RegisterType((*ChainTipReq)(nil), "proto.ChainTipReq")
	proto1.RegisterType((*ChainTipResp)(nil), "proto.ChainTipResp")
	proto1.RegisterType((*AddressResp)(nil), "proto.AddressResp")
	proto1.RegisterType((*TransferReq)(nil), "proto.TransferReq")
	proto1.RegisterType((*TransferResp)(nil), "proto.TransferResp")
	proto1.RegisterType((*NewAddressReq)(nil), "proto.NewAddressReq")
	proto1.RegisterType((*TransactionReq)(nil), "proto.TransactionReq")
	proto1.RegisterType((*TransactionResp)(nil), "proto.TransactionResp")
	proto1.RegisterType((*DeployTokenReq)(nil), "proto.DeployTokenReq")
	proto1.RegisterType((*GetTokenBalanceReq)(nil), "proto.GetTokenBalanceReq")
	proto1.RegisterType((*GetTokenBalanceResp)(nil), "proto.GetTokenBalanceResp")
	proto1.RegisterType((*TokenReq)(nil), "proto.TokenReq")
	proto1.RegisterType((*TokenResp)(nil), "proto.TokenResp")
	proto1.RegisterType((*TransactionErrorCallback)(nil), "proto.TransactionErrorCallback")
}

func init() { proto1.RegisterFile("wallet/private_wallet/private_wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6b, 0x13, 0x4d,
	0x14, 0x6e, 0x3e, 0x9b, 0x9c, 0x74, 0xd3, 0x97, 0x69, 0xdf, 0x12, 0x83, 0x62, 0x99, 0x52, 0xac,
	0x5e, 0xb4, 0x62, 0x11, 0xa4, 0x77, 0xfd, 0x52, 0x10, 0x14, 0x59, 0x0b, 0x8a, 0x37, 0x65, 0x92,
	0x3d, 0xba, 0x43, 0x37, 0x3b, 0xdb, 0x99, 0xd9, 0xa6, 0xbd, 0xf2, 0x77, 0xf9, 0xb3, 0xfc, 0x07,
	0xb2, 0xf3, 0xb1, 0xd9, 0x34, 0x2d, 0x0a, 0x7a, 0x95, 0x79, 0xce, 0x3e, 0xe7, 0x99, 0x67, 0x4e,
	0xce, 0x39, 0xf0, 0x6c, 0xca, 0x92, 0x04, 0xf5, 0x5e, 0x26, 0xf9, 0x15, 0xd3, 0x78, 0x7e, 0x27,
	0xdc, 0xcd, 0xa4, 0xd0, 0x82, 0xb4, 0xcc, 0x0f, 0x0d, 0xa0, 0x77, 0x1c, 0x33, 0x9e, 0x9e, 0xf1,
	0x2c, 0xc4, 0x4b, 0x7a, 0x00, 0x2b, 0x33, 0xa8, 0x32, 0xb2, 0x01, 0xed, 0x18, 0xf9, 0xb7, 0x58,
	0x0f, 0x6a, 0x9b, 0xb5, 0x9d, 0x20, 0x74, 0x88, 0x10, 0x68, 0xc6, 0x4c, 0xc5, 0x83, 0xfa, 0x66,
	0x6d, 0xa7, 0x1b, 0x9a, 0x33, 0x7d, 0x02, 0xbd, 0xc3, 0x28, 0x92, 0xa8, 0x94, 0x49, 0x1d, 0xc0,
	0x32, 0xb3, 0xd0, 0xe4, 0x76, 0x43, 0x0f, 0xe9, 0x3e, 0xf4, 0xce, 0x24, 0x4b, 0xd5, 0x57, 0x94,
	0x21, 0x5e, 0x92, 0x3e, 0xd4, 0xb5, 0x70, 0x9c, 0xba, 0x16, 0x64, 0x1d, 0x5a, 0x57, 0x2c, 0xc9,
	0xd1, 0x89, 0x5b, 0x40, 0x29, 0xac, 0xcc, 0x92, 0x54, 0x56, 0x3a, 0xa8, 0x55, 0x1c, 0x3c, 0x85,
	0xe0, 0x3d, 0x4e, 0x4b, 0x13, 0x97, 0x85, 0x87, 0x2c, 0x97, 0x99, 0x50, 0x68, 0x78, 0xad, 0xd0,
	0x43, 0xfa, 0xb3, 0x06, 0x7d, 0xa3, 0xc7, 0xc6, 0x9a, 0x8b, 0xb4, 0x20, 0x6f, 0x40, 0x9b, 0x4d,
	0x44, 0x9e, 0x6a, 0xa7, 0xe9, 0x50, 0xe1, 0x4f, 0xa5, 0xce, 0x4c, 0x5d, 0xa5, 0xe4, 0x21, 0x74,
	0x75, 0x2c, 0x51, 0xc5, 0x22, 0x89, 0x06, 0x0d, 0x23, 0x3b, 0x0b, 0x14, 0x57, 0x6a, 0x3e, 0x41,
	0x91, 0xeb, 0x41, 0x73, 0xb3, 0xb6, 0xd3, 0x08, 0x3d, 0x24, 0x5b, 0x10, 0x8c, 0xf2, 0x1b, 0x94,
	0xe7, 0xbe, 0x2c, 0x2d, 0x23, 0xb9, 0x62, 0x82, 0xce, 0x34, 0xd9, 0x86, 0xbe, 0xc2, 0x24, 0xa9,
	0xb0, 0xda, 0x86, 0x15, 0xd8, 0xa8, 0xa7, 0x6d, 0x41, 0xa0, 0xc5, 0x05, 0xa6, 0x25, 0x6b, 0xd9,
	0x6a, 0x99, 0xa0, 0x27, 0xd9, 0xc2, 0x76, 0x8c, 0xc3, 0xba, 0x16, 0x74, 0x1b, 0x56, 0xe7, 0x9e,
	0x6c, 0xab, 0xa8, 0xaf, 0x79, 0xe4, 0xab, 0x58, 0x9c, 0xe9, 0x67, 0xe8, 0x9f, 0x60, 0x96, 0x88,
	0x9b, 0xb3, 0x42, 0xac, 0xa8, 0x0c, 0x81, 0x66, 0xca, 0x26, 0xe8, 0x59, 0xc5, 0xb9, 0xa8, 0x96,
	0xba, 0x99, 0x8c, 0x44, 0xe2, 0x2a, 0xe3, 0x10, 0x19, 0x42, 0x27, 0xc2, 0x31, 0x9f, 0xb0, 0x44,
	0x99, 0xe2, 0x04, 0x61, 0x89, 0xe9, 0x17, 0x20, 0x6f, 0x50, 0x1b, 0xd9, 0x23, 0x96, 0xb0, 0x74,
	0x8c, 0x85, 0xfa, 0xc2, 0x5b, 0x6a, 0x77, 0xbc, 0xe5, 0x31, 0xf4, 0xa6, 0xb1, 0x28, 0x29, 0xf6,
	0x4e, 0x98, 0xc6, 0xc2, 0x11, 0xe8, 0x1e, 0xac, 0x2d, 0x68, 0xdb, 0x2e, 0x1c, 0x59, 0xe8, 0xbb,
	0xd0, 0x41, 0x1a, 0x43, 0xa7, 0x7c, 0xe0, 0x3f, 0xb1, 0x50, 0x69, 0xa0, 0x46, 0xb5, 0x81, 0x68,
	0x0f, 0xba, 0xee, 0x26, 0x95, 0xd1, 0xef, 0x30, 0xa8, 0xfc, 0x09, 0xa7, 0x52, 0x0a, 0x79, 0xcc,
	0x92, 0x64, 0xc4, 0xc6, 0x17, 0xe4, 0x11, 0x00, 0x57, 0xe7, 0x11, 0x66, 0x42, 0x71, 0xdb, 0x85,
	0x9d, 0xb0, 0xcb, 0xd5, 0x89, 0x0d, 0x2c, 0xba, 0xac, 0xff, 0xde, 0x65, 0xe3, 0xb6, 0xcb, 0x17,
	0x3f, 0x9a, 0xb0, 0xfe, 0xc1, 0x6e, 0x84, 0x4f, 0x66, 0x21, 0x7c, 0x44, 0x79, 0xc5, 0xc7, 0x48,
	0x5e, 0x42, 0xc7, 0xcf, 0x3e, 0x21, 0x76, 0x4b, 0xec, 0x56, 0x76, 0xc3, 0x70, 0x6d, 0x21, 0xa6,
	0x32, 0xba, 0x54, 0xa4, 0xf9, 0xc1, 0x2c, 0xd3, 0x2a, 0xe3, 0x5d, 0xa6, 0x55, 0xa7, 0x97, 0x2e,
	0x91, 0x57, 0x00, 0xb3, 0x59, 0x25, 0xeb, 0x8e, 0x34, 0x37, 0xbe, 0x43, 0x2f, 0x57, 0x59, 0x2b,
	0x74, 0x89, 0xbc, 0x86, 0xb5, 0xc3, 0x28, 0x32, 0x15, 0xad, 0x54, 0x92, 0xfc, 0x5f, 0xbd, 0xa7,
	0x9c, 0xea, 0xe1, 0xc6, 0x5d, 0x61, 0xa3, 0x73, 0x0a, 0xe4, 0xf4, 0x1a, 0xc7, 0xb9, 0xc6, 0xbf,
	0x92, 0x39, 0x80, 0x5e, 0x65, 0x5c, 0xca, 0xfc, 0xf9, 0x11, 0xba, 0xe7, 0x29, 0x6f, 0x61, 0xf5,
	0x56, 0xd3, 0x92, 0x07, 0x8e, 0xb8, 0x38, 0x28, 0xc3, 0xe1, 0x7d, 0x9f, 0x8c, 0xd6, 0x73, 0xe8,
	0xbe, 0xe3, 0xa9, 0xfd, 0x42, 0x56, 0xbd, 0x5d, 0x7f, 0xff, 0x7f, 0xf3, 0x01, 0x9f, 0x71, 0x94,
	0xcb, 0xf4, 0xcf, 0x33, 0x46, 0x6d, 0x13, 0xda, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x8c,
	0xc9, 0xb7, 0x69, 0x06, 0x00, 0x00,
}
