// This code was autogenerated from wallet/ethereum_wallet/ethereum_wallet.proto, do not edit.
package proto

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	nats "github.com/nats-io/go-nats"
	"github.com/nats-rpc/nrpc"
)

// EthereumWalletServiceServer is the interface that providers of the service
// EthereumWalletService should implement.
type EthereumWalletServiceServer interface {
	Deposit(ctx context.Context, req DepositReq) (resp DepositResp, err error)
	EtherWithdraw(ctx context.Context, req EtherWithdrawReq) (resp EtherWithdrawResp, err error)
	TokenWithdraw(ctx context.Context, req TokenWithdrawReq) (resp TokenWithdrawResp, err error)
}

// EthereumWalletServiceHandler provides a NATS subscription handler that can serve a
// subscription using a given EthereumWalletServiceServer implementation.
type EthereumWalletServiceHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  EthereumWalletServiceServer
}

func NewEthereumWalletServiceHandler(ctx context.Context, nc nrpc.NatsConn, s EthereumWalletServiceServer) *EthereumWalletServiceHandler {
	return &EthereumWalletServiceHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,
	}
}

func NewEthereumWalletServiceConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s EthereumWalletServiceServer) *EthereumWalletServiceHandler {
	return &EthereumWalletServiceHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

func (h *EthereumWalletServiceHandler) Subject() string {
	return "proto.EthereumWalletService.>"
}

func (h *EthereumWalletServiceHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"proto", 0, "EthereumWalletService", 0, msg.Subject)
	if err != nil {
		log.Printf("EthereumWalletServiceHanlder: EthereumWalletService subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "Deposit":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("DepositHanlder: Deposit subject parsing failed: %v", err)
			break
		}
		var req DepositReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("DepositHandler: Deposit request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.Deposit(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "EtherWithdraw":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("EtherWithdrawHanlder: EtherWithdraw subject parsing failed: %v", err)
			break
		}
		var req EtherWithdrawReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("EtherWithdrawHandler: EtherWithdraw request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.EtherWithdraw(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	case "TokenWithdraw":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("TokenWithdrawHanlder: TokenWithdraw subject parsing failed: %v", err)
			break
		}
		var req TokenWithdrawReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("TokenWithdrawHandler: TokenWithdraw request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.TokenWithdraw(ctx, req)
				if err != nil {
					return nil, err
				}
				return &innerResp, err
			}
		}
	default:
		log.Printf("EthereumWalletServiceHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("EthereumWalletServiceHandler: EthereumWalletService handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type EthereumWalletServiceClient struct {
	nc      nrpc.NatsConn
	PkgSubject string
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewEthereumWalletServiceClient(nc nrpc.NatsConn) *EthereumWalletServiceClient {
	return &EthereumWalletServiceClient{
		nc:      nc,
		PkgSubject: "proto",
		Subject: "EthereumWalletService",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *EthereumWalletServiceClient) Deposit(req DepositReq) (resp DepositResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "Deposit"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *EthereumWalletServiceClient) EtherWithdraw(req EtherWithdrawReq) (resp EtherWithdrawResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "EtherWithdraw"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

func (c *EthereumWalletServiceClient) TokenWithdraw(req TokenWithdrawReq) (resp TokenWithdrawResp, err error) {

	subject := c.PkgSubject + "." + c.Subject + "." + "TokenWithdraw"

	// call
	err = nrpc.Call(&req, &resp, c.nc, subject, c.Encoding, c.Timeout)
	if err != nil {
		return // already logged
	}

	return
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	pkgSubject string
	EthereumWalletService *EthereumWalletServiceClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
		pkgSubject: "proto",
	}
	c.EthereumWalletService = NewEthereumWalletServiceClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.EthereumWalletService != nil {
		c.EthereumWalletService.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.EthereumWalletService != nil {
		c.EthereumWalletService.Timeout = t
	}
}