// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/ethereum_wallet/ethereum_wallet.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	wallet/ethereum_wallet/ethereum_wallet.proto

It has these top-level messages:
	DepositReq
	DepositResp
	EtherWithdrawReq
	EtherWithdrawResp
	TokenWithdrawReq
	TokenWithdrawResp
	TransactionCallback
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DepositReq struct {
	Purpose int32 `protobuf:"varint,1,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *DepositReq) Reset()                    { *m = DepositReq{} }
func (m *DepositReq) String() string            { return proto1.CompactTextString(m) }
func (*DepositReq) ProtoMessage()               {}
func (*DepositReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DepositReq) GetPurpose() int32 {
	if m != nil {
		return m.Purpose
	}
	return 0
}

type DepositResp struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *DepositResp) Reset()                    { *m = DepositResp{} }
func (m *DepositResp) String() string            { return proto1.CompactTextString(m) }
func (*DepositResp) ProtoMessage()               {}
func (*DepositResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DepositResp) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type EtherWithdrawReq struct {
	To    string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *EtherWithdrawReq) Reset()                    { *m = EtherWithdrawReq{} }
func (m *EtherWithdrawReq) String() string            { return proto1.CompactTextString(m) }
func (*EtherWithdrawReq) ProtoMessage()               {}
func (*EtherWithdrawReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EtherWithdrawReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EtherWithdrawReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EtherWithdrawResp struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *EtherWithdrawResp) Reset()                    { *m = EtherWithdrawResp{} }
func (m *EtherWithdrawResp) String() string            { return proto1.CompactTextString(m) }
func (*EtherWithdrawResp) ProtoMessage()               {}
func (*EtherWithdrawResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EtherWithdrawResp) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type TokenWithdrawReq struct {
	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress" json:"token_address,omitempty"`
	To           string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Value        string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *TokenWithdrawReq) Reset()                    { *m = TokenWithdrawReq{} }
func (m *TokenWithdrawReq) String() string            { return proto1.CompactTextString(m) }
func (*TokenWithdrawReq) ProtoMessage()               {}
func (*TokenWithdrawReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TokenWithdrawReq) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *TokenWithdrawReq) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TokenWithdrawReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TokenWithdrawResp struct {
	Txid string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
}

func (m *TokenWithdrawResp) Reset()                    { *m = TokenWithdrawResp{} }
func (m *TokenWithdrawResp) String() string            { return proto1.CompactTextString(m) }
func (*TokenWithdrawResp) ProtoMessage()               {}
func (*TokenWithdrawResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TokenWithdrawResp) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

type TransactionCallback struct {
	IsDeposit bool   `protobuf:"varint,1,opt,name=is_deposit,json=isDeposit" json:"is_deposit,omitempty"`
	Txid      string `protobuf:"bytes,2,opt,name=txid" json:"txid,omitempty"`
	From      string `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	To        string `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Contract  string `protobuf:"bytes,5,opt,name=contract" json:"contract,omitempty"`
	Gas       uint64 `protobuf:"varint,6,opt,name=gas" json:"gas,omitempty"`
	GasPrice  string `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice" json:"gas_price,omitempty"`
	Status    uint64 `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
	Height    uint64 `protobuf:"varint,9,opt,name=height" json:"height,omitempty"`
	Value     string `protobuf:"bytes,10,opt,name=value" json:"value,omitempty"`
	BlockTime int64  `protobuf:"varint,11,opt,name=block_time,json=blockTime" json:"block_time,omitempty"`
}

func (m *TransactionCallback) Reset()                    { *m = TransactionCallback{} }
func (m *TransactionCallback) String() string            { return proto1.CompactTextString(m) }
func (*TransactionCallback) ProtoMessage()               {}
func (*TransactionCallback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TransactionCallback) GetIsDeposit() bool {
	if m != nil {
		return m.IsDeposit
	}
	return false
}

func (m *TransactionCallback) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionCallback) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionCallback) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionCallback) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *TransactionCallback) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *TransactionCallback) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *TransactionCallback) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TransactionCallback) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TransactionCallback) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TransactionCallback) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func init() {
	proto1.RegisterType((*DepositReq)(nil), "proto.DepositReq")
	proto1.RegisterType((*DepositResp)(nil), "proto.DepositResp")
	proto1.RegisterType((*EtherWithdrawReq)(nil), "proto.EtherWithdrawReq")
	proto1.RegisterType((*EtherWithdrawResp)(nil), "proto.EtherWithdrawResp")
	proto1.RegisterType((*TokenWithdrawReq)(nil), "proto.TokenWithdrawReq")
	proto1.RegisterType((*TokenWithdrawResp)(nil), "proto.TokenWithdrawResp")
	proto1.RegisterType((*TransactionCallback)(nil), "proto.TransactionCallback")
}

func init() { proto1.RegisterFile("wallet/ethereum_wallet/ethereum_wallet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xd2, 0xcf, 0xdc, 0x31, 0xd4, 0x99, 0x2f, 0xab, 0x08, 0xa9, 0x0a, 0x12, 0xeb, 0x03,
	0x1a, 0xd2, 0x78, 0xe1, 0x15, 0xb1, 0xbd, 0xa3, 0x50, 0x69, 0x4f, 0x28, 0x72, 0x13, 0xd3, 0x5a,
	0x4d, 0x62, 0x63, 0xdf, 0x6c, 0xfc, 0x18, 0xfe, 0x17, 0x7f, 0x07, 0xd9, 0x71, 0xd2, 0x35, 0xeb,
	0x9e, 0xea, 0x73, 0x7c, 0xee, 0xf1, 0xe9, 0xcd, 0x81, 0x8f, 0xf7, 0xac, 0x28, 0x38, 0x7e, 0xe2,
	0xb8, 0xe5, 0x9a, 0xd7, 0x65, 0x7a, 0x1c, 0x5f, 0x2a, 0x2d, 0x51, 0x92, 0x91, 0xfb, 0x89, 0x3f,
	0x00, 0x5c, 0x73, 0x25, 0x8d, 0xc0, 0x84, 0xff, 0x26, 0x14, 0x26, 0xaa, 0xd6, 0x4a, 0x1a, 0x4e,
	0x83, 0x45, 0xb0, 0x1c, 0x25, 0x2d, 0x8c, 0x2f, 0xe0, 0xb4, 0xd3, 0x19, 0x65, 0x85, 0x2c, 0xcf,
	0x35, 0x37, 0xc6, 0x09, 0xa3, 0xa4, 0x85, 0xf1, 0x17, 0x98, 0xdd, 0xd8, 0x07, 0x6f, 0x05, 0x6e,
	0x73, 0xcd, 0xee, 0xad, 0xed, 0x73, 0x08, 0x51, 0x7a, 0x61, 0x88, 0x92, 0xbc, 0x84, 0xd1, 0x1d,
	0x2b, 0x6a, 0x4e, 0x43, 0x47, 0x35, 0x20, 0xbe, 0x80, 0xf3, 0xde, 0xa4, 0x51, 0x84, 0xc0, 0x10,
	0xff, 0x88, 0xdc, 0x0f, 0xbb, 0x73, 0xfc, 0x13, 0x66, 0x2b, 0xb9, 0xe3, 0xd5, 0xc3, 0x27, 0xde,
	0xc3, 0x19, 0x5a, 0x2e, 0x3d, 0x8c, 0xf5, 0xcc, 0x91, 0x5f, 0x1b, 0xce, 0xe7, 0x08, 0x1f, 0xe7,
	0x18, 0xf4, 0x72, 0xf4, 0xec, 0x9f, 0xc8, 0xf1, 0x37, 0x84, 0x17, 0x2b, 0xcd, 0x2a, 0xc3, 0x32,
	0x14, 0xb2, 0xfa, 0xc6, 0x8a, 0x62, 0xcd, 0xb2, 0x1d, 0x79, 0x07, 0x20, 0x4c, 0x9a, 0x37, 0xeb,
	0x72, 0x13, 0xd3, 0x24, 0x12, 0xc6, 0xef, 0xaf, 0xb3, 0x0a, 0xf7, 0x56, 0x96, 0xfb, 0xa5, 0x65,
	0xe9, 0x83, 0xb8, 0xb3, 0x4f, 0x3b, 0xec, 0xd2, 0xce, 0x61, 0x9a, 0xc9, 0x0a, 0x35, 0xcb, 0x90,
	0x8e, 0x1c, 0xdb, 0x61, 0x32, 0x83, 0xc1, 0x86, 0x19, 0x3a, 0x5e, 0x04, 0xcb, 0x61, 0x62, 0x8f,
	0xe4, 0x2d, 0x44, 0x1b, 0x66, 0x52, 0xa5, 0x45, 0xc6, 0xe9, 0xa4, 0x91, 0x6f, 0x98, 0xf9, 0x6e,
	0x31, 0x79, 0x0d, 0x63, 0x83, 0x0c, 0x6b, 0x43, 0xa7, 0x6e, 0xc2, 0x23, 0xcb, 0x6f, 0xb9, 0xd8,
	0x6c, 0x91, 0x46, 0x0d, 0xdf, 0xa0, 0xfd, 0xa2, 0xe0, 0xc1, 0xa2, 0xec, 0xff, 0x5c, 0x17, 0x32,
	0xdb, 0xa5, 0x28, 0x4a, 0x4e, 0x4f, 0x17, 0xc1, 0x72, 0x90, 0x44, 0x8e, 0x59, 0x89, 0x92, 0x5f,
	0xfd, 0x0b, 0xe0, 0xd5, 0x8d, 0xef, 0xde, 0xad, 0xab, 0xde, 0x0f, 0xae, 0xef, 0xec, 0xf3, 0x57,
	0x30, 0x69, 0x97, 0x71, 0xde, 0xd4, 0xf1, 0x72, 0x5f, 0xc2, 0x39, 0xe9, 0x53, 0x46, 0xc5, 0x27,
	0xe4, 0x1a, 0xce, 0x0e, 0xda, 0x41, 0xde, 0x78, 0x59, 0xbf, 0x6d, 0x73, 0x7a, 0xfc, 0xa2, 0x75,
	0x39, 0xf8, 0xb6, 0x9d, 0x4b, 0xbf, 0x50, 0x9d, 0xcb, 0xa3, 0x2a, 0xc4, 0x27, 0xeb, 0xb1, 0xbb,
	0xfa, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x6b, 0x85, 0x81, 0x72, 0x03, 0x00, 0x00,
}
